# Docker requires superuser permissions
sudo: 'required'
language: 'generic'

services:
  - 'docker'

before_install:
  - 'docker build -t rickyromero/react-production-workflow -f Dockerfile.dev ./frontend'

script:
  - 'docker run -e CI=true -v /usr/app/node_modules -v $(pwd)/frontend:/usr/app rickyromero/react-production-workflow yarn test'
